flopfarm/flopfarm/urls.py
"""flopfarm URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

# Use include() to add paths from the catalog application
from django.urls import include

urlpatterns += [
    path('flopfarm_admin/', include('flopfarm_admin.urls')),
]

#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='flopfarm_admin/', permanent=True)),
]

# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

#Add Django site authentication urls (for login, logout, password management)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

flopfarm/flopfarm_admin/urls.py
'''
Author: your name
Date: 2021-04-29 21:33:43
LastEditTime: 2021-05-04 12:52:25
LastEditors: Please set LastEditors
Description: In User Settings Edit
FilePath: /FlopFarmAdminLTE/flopfarm/flopfarm_admin/urls.py
'''

from django.urls import path
from . import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('market/', views.market, name = 'market'),
    path('purchased/', views.purchased, name = 'purchased'),
    path('market/<uuid:pk>/buy/', views.buy, name = 'buy'),
    path('idle_instance/upload/', views.upload.as_view(), name = 'upload'),
    path('running_instance/', views.running_instance, name = 'running_instance'),
    path('idle_instance/', views.idle_instance, name = 'idle_instance'),
]

flopfarm/flopfarm_admin/models.py
'''
Author: your name
Date: 2021-04-29 21:25:00
LastEditTime: 2021-05-06 19:34:42
LastEditors: Please set LastEditors
Description: In User Settings Edit
FilePath: /FlopFarmAdminLTE/flopfarm/flopfarm_admin/models.py
'''
from django.db import models
import uuid
from django.contrib.auth.models import User
import datetime

from django.db.models.deletion import CASCADE

class ETHaddress(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    address = models.CharField(max_length=200, blank = True, null = True, help_text='The ETH Address')

class Instance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular instance')
    name = models.CharField(max_length=200, help_text='Enter the instance name')
    
    TYPE = (
        ('c', 'General Computing Instance'),
        ('d', 'Deep Learning API')
    )

    STATUS = (
        ('o', 'offline'),
        ('i', 'Idle'),
        ('r', 'Running'),
    )

    type = models.CharField(
        max_length=1, 
        choices = TYPE, 
        blank = True, 
        default = 'c', 
        help_text='Instance type'
    )

    status = models.CharField(
        max_length=1, 
        choices = STATUS, 
        blank = True, 
        default = 'i', 
        help_text='Instance status'
    )


    OS = models.CharField(max_length=200, blank = True, null = True, help_text='Enter the Operating System info')
    CPU = models.CharField(max_length=200, blank = True, null = True, help_text='Enter the CPU info')
    GPU = models.CharField(max_length=200, blank = True, null = True, help_text='Enter the GPU info')
    RAM = models.CharField(max_length=200, blank = True, null = True, help_text='Enter the RAM info')
    hourly_price = models.FloatField(blank = True, null = True, help_text='Enter the hourly price')
    s_time = models.DateTimeField(blank = True, null = True, help_text = 'Start running time')
    e_time = models.DateTimeField(blank = True, null = True, help_text = 'end running time')
    IP = models.CharField(max_length=200, blank = True, null = True, help_text='Enter IP')
    username = models.CharField(max_length=200, blank = True, null = True, help_text='Enter SSH user name')
    password = models.CharField(max_length=200, blank = True, null = True, help_text='Enter SSH password')

    APIinfo = models.CharField(max_length=200,blank = True, null = True, help_text='Enter the API info')
    API_price = models.FloatField(blank = True, null = True, help_text='Enter the price per use for API')

    remarks = models.CharField(max_length=200, blank = True, null = True, help_text='Enter the remarks')

    provider = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='Instance_provided')
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank = True, null=True, related_name='Instance_using')

    def get_remaining_time(self):
        tzinfo = datetime.timezone(datetime.timedelta(hours = 8))
        return self.e_time - datetime.datetime.now(tzinfo)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-type']

flopfarm/flopfarm_admin/forms.py
'''
Author: your name
Date: 2021-05-02 16:52:59
LastEditTime: 2021-05-04 12:55:44
LastEditors: Please set LastEditors
Description: In User Settings Edit
FilePath: /FlopFarmDjango/flopfarm/flopfarm_admin/forms.py
'''
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _ 
class BuyInstanceForm(forms.Form):
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        self.instance = kwargs.pop('instance', None)
        super(BuyInstanceForm, self).__init__(*args, **kwargs)

    expect_time = forms.FloatField(help_text="Enter the expected using time (in hour)")

    def clean_expect_time(self):
        data = self.cleaned_data['expect_time']
        if ((data == None) and (self.instance.type == 'c')):
            raise ValidationError(_('Invalid using time: the using time is required'))

        if (data <= 0):
            raise ValidationError(_('Invalid using time: the using time should be positive.'))

        return data

flopfarm/flopfarm_admin/views.py
'''
Author: your name
Date: 2021-04-29 21:25:00
LastEditTime: 2021-05-04 17:33:56
LastEditors: Please set LastEditors
Description: In User Settings Edit
FilePath: /FlopFarmAdminLTE/flopfarm/flopfarm_admin/views.py
'''
from django.shortcuts import render

# Create your views here.
from .models import Instance, ETHaddress
from django.contrib.auth.decorators import login_required

from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse

from .forms import BuyInstanceForm

from django.views.generic.edit import CreateView
from django.urls import reverse_lazy


@login_required
def dashboard(request):
    instance = Instance.objects.filter(status = 'i')
    
    context = {
        'instance' : instance
    }

    address = ETHaddress.objects.filter(user = request.user)
    context['address'] = address[0].address

    return render(request, 'dashboard.html', context=context)

@login_required
def market(request):
    instance = Instance.objects.filter(status = 'i')
    
    context = {
        'instance' : instance
    }

    address = ETHaddress.objects.filter(user = request.user)
    context['address'] = address[0].address
    
    return render(request, 'market.html', context=context)

@login_required
def purchased(request):
    instance = Instance.objects.filter(user = request.user)
    
    context = {
        'instance' : instance
    }

    address = ETHaddress.objects.filter(user = request.user)
    context['address'] = address[0].address

    return render(request, 'purchased.html', context=context)

@login_required
def running_instance(request):
    instance = Instance.objects.filter(status = 'r')
    
    context = {
        'instance' : instance
    }

    address = ETHaddress.objects.filter(user = request.user)
    context['address'] = address[0].address

    return render(request, 'running_instance.html', context=context)

@login_required
def idle_instance(request):
    instance = Instance.objects.filter(status = 'i')
    
    context = {
        'instance' : instance
    }

    address = ETHaddress.objects.filter(user = request.user)
    context['address'] = address[0].address

    return render(request, 'idle_instance.html', context=context)

import datetime

@login_required
def buy(request, pk):
    instance = get_object_or_404(Instance, pk=pk)

    if request.method == 'POST' :
        
        form = BuyInstanceForm(request.POST, user = request.user, instance = instance)

        if form.is_valid():
            instance.user = request.user
            instance.status = 'r'
            instance.s_time = datetime.datetime.now()
            instance.e_time = datetime.datetime.now() + datetime.timedelta(hours = form.cleaned_data['expect_time'])
            instance.save()
            return HttpResponseRedirect(reverse('purchased'))
    
    else:

        form = BuyInstanceForm(initial = {'expect_time' : 0})

    context = {
        'form' : form,
        'instance' : instance,
    }

    address = ETHaddress.objects.filter(user = request.user)
    context['address'] = address[0].address

    return render(request, 'buy.html', context = context)

from django import http

class upload(CreateView):
    model = Instance
    fields = ['type', 'name', 'OS', 'CPU', 'GPU', 'RAM', 'hourly_price', 'IP', 'username', 'password', 'APIinfo', 'API_price', 'remarks']

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.provider = self.request.user
        obj.save()     
        return http.HttpResponseRedirect(reverse('idle_instance'))
    
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['address'] = (ETHaddress.objects.filter(user = self.request.user))[0].address
        return context

flopfarm/flopfarm_admin/templates/buy.html
<!--
 * @Author: your name
 * @Date: 2021-05-02 17:16:52
 * @LastEditTime: 2021-05-06 21:10:55
 * @LastEditors: Please set LastEditors
 * @Description: In User Settings Edit
 * @FilePath: /FlopFarmDjango/flopfarm/flopfarm_admin/templates/buy.html
-->
{% extends "temp.html" %}

{% load static %}

{% block frontjs %}
<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
{% endblock %}

{% block title %}
FlopFarm | Confirm Order
{% endblock %}

{% block side_navi %}
<!-- Sidebar Menu -->
<nav class="mt-2">
  <ul
    class="nav nav-pills nav-sidebar flex-column"
    data-widget="treeview"
    role="menu"
    data-accordion="false"
  >
    <!-- Add icons to the links using the .nav-icon class
            with font-awesome or any other icon font library -->
    <li class="nav-item">
      <a href="{% url 'dashboard' %}" class="nav-link">
        <i class="nav-icon fas fa-tachometer-alt"></i>
        <p>Dashboard&#128640;</p>
      </a>
    </li>
    <li class="nav-item menu-open">
      <a href="edge.html" class="nav-link">
        <i class="far fa-circle nav-icon"></i>
        <p>
          Edge
          <i class="right fas fa-angle-left"></i>
        </p>
      </a>
      <ul class="nav nav-treeview">
        <li class="nav-item">
          <a href="{% url 'idle_instance' %}" class="nav-link">
            <i class="far fa-circle nav-icon"></i>
            <p>Idle Instance</p>
          </a>
        </li>
        <li class="nav-item">
          <a href="{% url 'running_instance' %}" class="nav-link">
            <i class="far fa-circle nav-icon"></i>
            <p>Running Instance</p>
          </a>
        </li>
      </ul>
    </li>
    <li class="nav-item menu-open">
      <a href="{% url 'market' %}" class="nav-link">
        <i class="far fa-circle nav-icon"></i>
        <p>
          User
          <i class="right fas fa-angle-left"></i>
        </p>
      </a>
      <ul class="nav nav-treeview">
        <li class="nav-item">
          <a href="{% url 'market' %}" class="nav-link">
            <i class="far fa-circle nav-icon"></i>
            <p>Market</p>
          </a>
        </li>
        <li class="nav-item">
          <a href="{% url 'purchased' %}" class="nav-link">
            <i class="far fa-circle nav-icon"></i>
            <p>Purchased</p>
          </a>
        </li>
      </ul>
    </li>
  </ul>
</nav>
<!-- /.sidebar-menu -->
{% endblock %}


{% block content %}
  <!-- =========================================================== -->
  <div class="content-header">
    <h1>Confirm your order:</h1>
  </div>
  <div class="row" id = "Ava_ins">

  <!-- =========================================================== -->
  <div class="col-md-5">
    {% if instance.type == "d" %}

      <div class="card card-success shadow-lg"> <!--Change color here: default, primary, secondary, success, info, danger, warning-->
      {% elif instance.type == "c" %}
      <div class="card card-primary shadow-lg"> <!--Change color here: default, primary, secondary, success, info, danger, warning-->
      {% endif %}
        <div class="card-header">
          <h3 class="card-title">{{ instance.name }}</h3>
          <!-- /.card-tools -->
        </div>
        <!-- /.card-header -->
        <div class="card-body">
          <p style="color:lightseagreen;">{{ instance.get_type_display }}</p>

          {% if instance.type == "d" %}
          <li>{{ instance.APIinfo }}</li>
          <img class="card-img-top" src="{% static 'img/AnimeAPI.webp' %}" alt="AnimeAPI">

          {% elif instance.type == "c" %}
          <li>OS: {{ instance.OS }}</li>
          <li>CPU: {{ instance.CPU }}</li>
          <li>GPU: {{ instance.GPU }}</li>
          <li>RAM: {{ instance.RAM }}</li>
          {% endif %}

          <li>Remarks: {{ instance.remarks }}</li>
          <p></p>
          {% if instance.type == "d" %}
          <p style="color: indianred; font-size: 25px;">{{ instance.API_price }} ETH/access</p>
          {% elif instance.type == "c" %}
          <p style="color: indianred; font-size: 25px;">{{ instance.hourly_price }} ETH/hour</p>
          {% endif %}

          <div class="card card-general">
            <div class="card-header">
              <h3 class="card-title">Place an order</h3>
            </div>
            </card-header>
            <!-- form start -->
            <form action = "" method = "post">
              {% csrf_token %}

              <div class="card-body">
        
              {% if instance.type == "d" %}

              <!-- {{ form.as_table }} -->
              <div class="form-group">
                <label for="exampleInputFile">File input</label>
                <div class="input-group">
                  <div class="custom-file">
                    <input type="file" class="custom-file-input" id="exampleInputFile">
                    <label class="custom-file-label" for="exampleInputFile">Choose file</label>
                  </div>
                  <div class="input-group-append">
                    <span class="input-group-text">Upload</span>
                  </div>
                </div>
              </div>
                <p>You need to pay</p>
                <p style="color: indianred; font-size: 25px;">{{ instance.API_price }} ETH</p>
              {% elif instance.type == "c" %}
              
              {{ form.as_table }}
        
              <p>You need to pay</p>
              <p id = "PAY" style="color: indianred; font-size: 25px;">0 ETH</p>
              <script>
                $(document).ready(function(){
                  $("#id_expect_time").change(function(){
                    t = $("#id_expect_time").val();
                    window.pay = {{ instance.hourly_price }} * t;
                    paystr = pay.toString();
                    $("#PAY").text(paystr + " ETH");
                  });
                });
              </script>
              {% endif %}
              <div class="card-footer">
                <a class="btn btn-success" onclick="Send()">Pay</a>
                <button type="submit" class="btn btn-primary">I have paid</button>
              </div>
              </div>
            </form>
          </div>
        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.card -->
  </div>

{% endblock %}

{% block js %}
{% endblock %}

flopfarm/flopfarm_admin/templates/idle_instance.html
{% extends "temp.html" %} {% load static %} {% block frontjs %} {% endblock %}
{% block title %} FlopFarm | Purchased {% endblock %} {% block side_navi %}

<!-- Sidebar Menu -->
<nav class="mt-2">
  <ul
    class="nav nav-pills nav-sidebar flex-column"
    data-widget="treeview"
    role="menu"
    data-accordion="false"
  >
    <!-- Add icons to the links using the .nav-icon class
            with font-awesome or any other icon font library -->
    <li class="nav-item">
      <a href="{% url 'dashboard' %}" class="nav-link">
        <i class="nav-icon fas fa-tachometer-alt"></i>
        <p>Dashboard&#128640;</p>
      </a>
    </li>
    <li class="nav-item menu-open">
      <a href="{% url 'dashboard' %}" class="nav-link">
        <i class="far fa-circle nav-icon"></i>
        <p>
          Edge
          <i class="right fas fa-angle-left"></i>
        </p>
      </a>
      <ul class="nav nav-treeview">
        <li class="nav-item">
          <a href="{% url 'idle_instance' %}" class="nav-link active">
            <i class="far fa-circle nav-icon"></i>
            <p>Idle Instance</p>
          </a>
        </li>
        <li class="nav-item">
          <a href="{% url 'running_instance' %}" class="nav-link">
            <i class="far fa-circle nav-icon"></i>
            <p>Running Instance</p>
          </a>
        </li>
      </ul>
    </li>
    <li class="nav-item menu-open">
      <a href="{% url 'market' %}" class="nav-link">
        <i class="far fa-circle nav-icon"></i>
        <p>
          User
          <i class="right fas fa-angle-left"></i>
        </p>
      </a>
      <ul class="nav nav-treeview">
        <li class="nav-item">
          <a href="{% url 'market' %}" class="nav-link">
            <i class="far fa-circle nav-icon"></i>
            <p>Market</p>
          </a>
        </li>
        <li class="nav-item">
          <a href="{% url 'purchased' %}" class="nav-link">
            <i class="far fa-circle nav-icon"></i>
            <p>Purchased</p>
          </a>
        </li>
      </ul>
    </li>
  </ul>
</nav>
<!-- /.sidebar-menu -->
<!-- /.sidebar-menu -->
{% endblock %} {% block content %}
<div class="content-header">
  <h1>My Idle Instance</h1>
</div>
<div class="content-header">
  <a href="{% url 'upload' %}" class="btn btn-success">Upload New Edge</a>
</div>

<div class="row" id = "Ava_ins">
  {% for ins in instance %}
  {% if ins.provider == user %}
  {% if ins.status == "i" %}
  <div class="col-md-5">
    {% if ins.type == "d" %}
    <div class="card card-success shadow-lg ">
      <!--Change color here: default, primary, secondary, success, info, danger, warning-->
      {% elif ins.type == "c" %}
      <div class="card card-primary shadow-lg ">
        <!--Change color here: default, primary, secondary, success, info, danger, warning-->
        {% endif %}
        <div class="card-header">
          <h3 class="card-title">{{ ins.name }}</h3>
          <div class="card-tools">
            <button
              type="button"
              class="btn btn-tool"
              data-card-widget="collapse"
            >
              <i class="fas fa-plus"></i>
            </button>
          </div>
          <!-- /.card-tools -->
        </div>
        <!-- /.card-header -->
        <div class="card-body">
          <p style="color: lightseagreen">{{ ins.get_type_display }}</p>

          {% if ins.type == "d" %}
          <li>{{ ins.APIinfo }}</li>
          {% elif ins.type == "c" %}
          <li>OS: {{ ins.OS }}</li>
          <li>CPU: {{ ins.CPU }}</li>
          <li>GPU: {{ ins.GPU }}</li>
          <li>RAM: {{ ins.RAM }}</li>
          {% endif %}

          <li>Remarks: {{ ins.remarks }}</li>
          <p></p>

          {% if ins.type == "d" %}
          <p style="color: indianred; font-size: 25px">
            {{ ins.API_price }} ETH/access
          </p>
          {% elif ins.type == "c" %}
          <p style="color: indianred; font-size: 25px">
            {{ ins.hourly_price }} ETH/hour
          </p>
          {% endif %}
          <div class="card-footer">
            {% if ins.status == "o" %}
            <button type="submit" class="btn btn-success">go online</button>
            {% elif ins.status == "i" %}
            <button type="submit" class="btn btn-danger">go offline</button>
            {% endif %}
          </div>
        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.card -->
    </div>
    <!-- /.col -->
    {% endif %}
    {% endif %}
    {% endfor %} 


</div>
<!-- /.row -->


</div>
<!-- /.row -->
{% endblock %} {% block js %} {% endblock %}

flopfarm/flopfarm_admin/templates/market.html
{% extends "temp.html" %}

{% load static %}

<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
{% block frontjs %}
{% endblock %}

{% block title %}
FlopFarm | Market
{% endblock %}

{% block side_navi %}

<!-- Sidebar Menu -->
<nav class="mt-2">
  <ul
    class="nav nav-pills nav-sidebar flex-column"
    data-widget="treeview"
    role="menu"
    data-accordion="false"
  >
    <!-- Add icons to the links using the .nav-icon class
            with font-awesome or any other icon font library -->
    <li class="nav-item">
      <a href="{% url 'dashboard' %}" class="nav-link">
        <i class="nav-icon fas fa-tachometer-alt"></i>
        <p>Dashboard&#128640;</p>
      </a>
    </li>
    <li class="nav-item menu-open">
      <a href="{% url 'idle_instance' %}" class="nav-link">
        <i class="far fa-circle nav-icon"></i>
        <p>
          Edge
          <i class="right fas fa-angle-left"></i>
        </p>
      </a>
      <ul class="nav nav-treeview">
        <li class="nav-item">
          <a href="{% url 'idle_instance' %}" class="nav-link">
            <i class="far fa-circle nav-icon"></i>
            <p>Idle Instance</p>
          </a>
        </li>
        <li class="nav-item">
          <a href="{% url 'running_instance' %}" class="nav-link">
            <i class="far fa-circle nav-icon"></i>
            <p>Running Instance</p>
          </a>
        </li>
      </ul>
    </li>
    <li class="nav-item menu-open">
      <a href="{% url 'market' %}" class="nav-link">
        <i class="far fa-circle nav-icon"></i>
        <p>
          User
          <i class="right fas fa-angle-left"></i>
        </p>
      </a>
      <ul class="nav nav-treeview">
        <li class="nav-item">
          <a href="{% url 'market' %}" class="nav-link active">
            <i class="far fa-circle nav-icon"></i>
            <p>Market</p>
          </a>
        </li>
        <li class="nav-item">
          <a href="{% url 'purchased' %}" class="nav-link">
            <i class="far fa-circle nav-icon"></i>
            <p>Purchased</p>
          </a>
        </li>
      </ul>
    </li>
  </ul>
</nav>
<!-- /.sidebar-menu -->
{% endblock %} 

{% block content %}
<!-- =========================================================== -->
<div class="content-header">
  <h1>Market</h1>
</div>

<div class="row" id="Ava_ins">
  <!-- =========================================================== -->

  {% for ins in instance %}
  {% if ins.provider != user %}
  {% if ins.type == "c" %}
  <div class="col-md-5">
    {% if ins.type == "d" %}
    <div class="card card-success shadow-lg ">
      <!--Change color here: default, primary, secondary, success, info, danger, warning-->
      {% elif ins.type == "c" %}
      <div class="card card-primary shadow-lg ">
        <!--Change color here: default, primary, secondary, success, info, danger, warning-->
        {% endif %}
        <div class="card-header">
          <h3 class="card-title">{{ ins.name }}</h3>
          <div class="card-tools">
            <button
              type="button"
              class="btn btn-tool"
              data-card-widget="collapse"
            >
              <i class="fas fa-plus"></i>
            </button>
          </div>
          <!-- /.card-tools -->
        </div>
        <!-- /.card-header -->
        <div class="card-body">
          <p style="color: lightseagreen">{{ ins.get_type_display }}</p>

          {% if ins.type == "d" %}
          <li>{{ ins.APIinfo }}</li>
          <img class="card-img-top"   height="350" 
          src="{% static 'img/AnimeAPI.webp' %}" alt="AnimeAPI">

          {% elif ins.type == "c" %}
          <li>OS: {{ ins.OS }}</li>
          <li>CPU: {{ ins.CPU }}</li>
          <li>GPU: {{ ins.GPU }}</li>
          <li>RAM: {{ ins.RAM }}</li>
          {% endif %}

          <li>Remarks: {{ ins.remarks }}</li>
          <p></p>

          {% if ins.type == "d" %}
          <p style="color: indianred; font-size: 25px">
            {{ ins.API_price }} ETH/access
          </p>
          {% elif ins.type == "c" %}
          <p style="color: indianred; font-size: 25px">
            {{ ins.hourly_price }} ETH/hour
          </p>
          {% endif %}
          <div class="card-footer">
            <a href = "{% url 'buy' ins.id %}" class="btn btn-success">Buy</a>
          </div>
        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.card -->
    </div>
    <!-- /.col -->
    {% endif %}
    {% endif %}
    {% endfor %}

    {% for ins in instance %}
    {% if ins.provider != user %}
    {% if ins.type == "d" %}
    <div class="col-md-5">
      {% if ins.type == "d" %}
      <div class="card card-success shadow-lg ">
        <!--Change color here: default, primary, secondary, success, info, danger, warning-->
        {% elif ins.type == "c" %}
        <div class="card card-primary shadow-lg ">
          <!--Change color here: default, primary, secondary, success, info, danger, warning-->
          {% endif %}
          <div class="card-header">
            <h3 class="card-title">{{ ins.name }}</h3>
            <div class="card-tools">
              <button
                type="button"
                class="btn btn-tool"
                data-card-widget="collapse"
              >
                <i class="fas fa-plus"></i>
              </button>
            </div>
            <!-- /.card-tools -->
          </div>
          <!-- /.card-header -->
          <div class="card-body">
            <p style="color: lightseagreen">{{ ins.get_type_display }}</p>
  
            {% if ins.type == "d" %}
            <li>{{ ins.APIinfo }}</li>
            <img class="card-img-top"   height="350" 
            src="{% static 'img/AnimeAPI.webp' %}" alt="AnimeAPI">
  
            {% elif ins.type == "c" %}
            <li>OS: {{ ins.OS }}</li>
            <li>CPU: {{ ins.CPU }}</li>
            <li>GPU: {{ ins.GPU }}</li>
            <li>RAM: {{ ins.RAM }}</li>
            {% endif %}
  
            <li>Remarks: {{ ins.remarks }}</li>
            <p></p>
  
            {% if ins.type == "d" %}
            <p style="color: indianred; font-size: 25px">
              {{ ins.API_price }} ETH/access
            </p>
            {% elif ins.type == "c" %}
            <p style="color: indianred; font-size: 25px">
              {{ ins.hourly_price }} ETH/hour
            </p>
            {% endif %}
            <div class="card-footer">
              <a href = "{% url 'buy' ins.id %}" class="btn btn-success">Buy</a>
            </div>
          </div>
          <!-- /.card-body -->
        </div>
        <!-- /.card -->
      </div>
      <!-- /.col -->
      {% endif %}
      {% endif %}
      {% endfor %}
    {% endblock %} {% block js %} {% endblock %}
  </div>
</div>